resources:
  - deployment1.yaml
namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
commonLabels:
  app: bingo
  mydept: devops
commonAnnotations:
  oncallPager: 800-555-1212
patchesStrategicMerge:
  - replicas.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  path: patch.yaml
