resources:
  - deployment1.yaml
  - service.yaml
namespace: my-namespace
namePrefix: dev-
nameSuffix: "-001"
configMapGenerator:
  - name: myconfigmap
    literals:
      - name="dinggond"
commonLabels:
  app: bingo
  mydept: devops
commonAnnotations:
  oncallPager: 800-555-1212
patchesStrategicMerge:
  - replicas.yaml
patchesJson6902:
- target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-deployment
  path: patch.yaml
images:
 - name: nginx
   newName: mynginx
   newTag: 1.0.0
vars:
- name: MY_SERVICE_NAME
  objref:
    kind: Service
    name: my-nginx
    apiVersion: v1   
- name: CONFIG_MAP_NAME
  value: 
